excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cafecodificado.github.io
title: Café Codificado
email: 
author: cafecodificado
description: Manhãs são para café e codificação
paginate: 5
google_analytics: 