excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cafecodificado.github.io
title: Awesome
email: 
author: cafecodificado
description: My awesome new site
paginate: 5
google_analytics: 