excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://debugando.github.io
title: Debugando
email: 
author: godrix
description: Manhãs são para café e codificação
paginate: 5
google_analytics: 
